import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'; 
import axios from 'axios';

export default function Home() {

  const [location, setLocation] = useState('');
  const [data, setData] = useState({});
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');

  var apiKey = "f13ce6f2dd17c6f04a5c7d2bde365072";
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;
  console.log(url)

  const searchLocation = (event) => {
    if(event.key === "Enter") {
      axios.get(url)
      .then((response)=> {
        console.clear()
        setData(response.data);
        console.log(response.data);
        setWeather(response.data.weather);
        setErrorMessage("")
      }).catch(err => {
        console.log(err);
        setErrorMessage("Please enter another location");
        setData({});
        setWeather()
      })
      setLocation('')
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className={styles.main}>
        {data.name}
        <input
         value = {location}
         onChange= {event => setLocation(event.target.value)}
         placeholder = "Enter Location"
         onKeyDown= {searchLocation}
         type= "text"
        />

        {
          weather && weather.map((w, index) => {
            return (
              <div key={index}>
                <div>{w.description}</div>
                <div>{w.main}</div>
              </div>
            )
          })
        }
      </main>
    </>
  )
}

