import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'
import axios from 'axios'

export default function Home() {
  const [location, setLocation] = useState('');
  const [data, setData] = useState({});
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');

  var apiKey = `c0a7bc3f20580a835bc58de51fc14796`;
  var lang = "fr";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q${location}&units=${units}&appit=${apiKey}&lang=${lang}`

  
  const searchLocation = (event) => {
    if (event.key === "enter") {
      axios.get(url)
      .then((response) => {
        console.clear();
        setData(response.data);
        console.log(response.data);
        setWeather(response.dara.weather);
      })
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data.name}
        <input 
        value = {location}
        onChange = {event => setLocation(event.target.value)}
        placeholder="enter location"
        onKeyDown={searchLocation}
        type="text"
        />

        {
          weather && weather.map((w, index) =>{
            return (
              <div key ={index}>
                <div>{w.description}</div>
                <div>{w.main}</div>
              </div>
            )
          })
        }
      </main>

    </div>
  )
}
